from lcapy import *
import sympy as sp
import numpy as np
import os
import time

print("Questão 10")
print("a)")
print("Gabarito")
x1_n = -u(n) - (-1)**(n) * u(n)
sp.pprint(x1_n)
print("x[n]:")
sp.pprint(x1_n.seq((10,10)))
print("\n") 
print("***")
print("\n") 
print("Minha resposta")
x2_n = -u(n) - (-1)**(n) * u(n)
sp.pprint(x2_n)
print("x[n]:")
sp.pprint(x2_n.seq((-10,10)))
print("--------------------------------------------")
print("\n") 

print("b)")
print("Gabarito")
x_n = -u(-n-1) + (-1)**(n) * u(-n-1)
sp.pprint(x_n)
print("x[n]")
sp.pprint(x_n.seq((-10,10)))
print("\n") 
print("***")
print("\n") 
print("Minha resposta")
x_n = -u(-n-1) + (-1)**(n) * u(-n-1)
sp.pprint(x_n)
print("x[n]")
sp.pprint(x_n.seq((-10,10)))
print("--------------------------------------------")
print("\n") 

print("c)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("\n") 

print("d)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("\n") 

print("e)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("\n") 

print("f)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("\n") 

print("g)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("\n") 

print("h)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("\n") 

print("i)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("\n") 


time.sleep(20)
os.system('clear')