print("Questão 10")
print("a)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("/n")

print("b)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("/n")

print("c)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("/n")

print("d)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("/n")

print("e)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("/n")

print("f)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("/n")

print("g)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("/n")

print("h)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("/n")

print("i)")
print("Gabarito")
print("Minha resposta")
print("--------------------------------------------")
print("/n")
