from lcapy import *
import sympy as sp
import numpy as np
import os
import time

print("Questão 14")
print("a)")
print("Gabarito")
x1_n = 4 * (1/2)**(n) * u(n-1)
sp.pprint(x1_n)
print("x[n]:")
sp.pprint(x1_n.seq((-10,10)))
print("\n") 
print("***")
print("\n") 
print("Minha resposta")
x2_n = 2 * (1/2)**(n-1) * u(n-1)
sp.pprint(x2_n)
print("x[n]:")
sp.pprint(x2_n.seq((-10,10)))
print("--------------------------------------------")
print("\n") 

time.sleep(1)
os.system('clear')

print("b)")
print("Gabarito")
x1_n = delta(n) - delta(n-2) + delta(n-4) - delta(n-6)
sp.pprint(x1_n)
print("x[n]:")
sp.pprint(x1_n.seq((-10,10)))
print("\n") 
print("***")
print("\n") 
print("Minha resposta")
x2_n = delta(n) - delta(n-2) + delta(n-4) - delta(n-6)
sp.pprint(x2_n)
print("x[n]:")
sp.pprint(x2_n.seq((-10,10)))
print("--------------------------------------------")
print("\n") 

time.sleep(1)
os.system('clear')

print("c)")
print("Gabarito")
x1_n = -2 * (-1/2)**(n) * u(n) + (3/4)**(n) * u(n)
sp.pprint(x1_n)
print("x[n]:")
sp.pprint(x1_n.seq((-10,10)))
print("\n") 
print("***")
print("\n") 
print("Minha resposta")
x2_n = (-1/2)**(n-1) * u(n-1) + (3/4) * (3/4)**(n-1) * u(n-1)
sp.pprint(x2_n)
print("x[n]:")
sp.pprint(x2_n.seq((-10,10)))
print("\n") 
print("***")
print("\n") 
print("Automático")
X_z = (-1 * z**2 + 2 * z)/(z**2 - (1/4)*z - 3/8)
X_fat = X_z.factored()
sp.pprint(X_fat)
X_frac = X_fat.partfrac() 
sp.pprint(X_frac)
x_n = X_z(n)
sp.pprint(x_n)
print("x[n]:")
sp.pprint(x_n.seq((-10,10)))
print("--------------------------------------------")
print("\n") 

time.sleep(40)
os.system('clear')

print("d)")
print("Gabarito")
x1_n = ((9+4*sqrt(5))/(4*sqrt(5))) * (((2+2*sqrt(5))/5))**(n) * u(n) + ((4*sqrt(5)-9)/(4*sqrt(5))) * (((2-2*sqrt(5))/5))**(n) * u(n)
sp.pprint(x1_n)
print("x[n]:")
sp.pprint(x1_n.seq((-10,10)))
print("\n") 
print("***")
print("\n") 
print("Minha resposta")
x2_n = (84/25) * (8/5)**(n-1) * u(n-1) + (1/25) * (-2/5)**(n-1) * u(n-1)
sp.pprint(x2_n)
print("x[n]:")
sp.pprint(x2_n.seq((-10,10)))
print("\n") 
print("***")
print("\n") 
print("Automático")
X_z = (2 * z**2 + z)/(z**2 - (6/5)*z - 16/25)
X_fat = X_z.factored()
sp.pprint(X_fat)
X_frac = X_fat.partfrac() 
sp.pprint(X_frac)
x_n = X_z(n)
sp.pprint(x_n)
print("x[n]:")
sp.pprint(x_n.seq((-10,10)))

print("--------------------------------------------")
print("\n") 

time.sleep(3)
os.system('clear')